### ISSUE TITLE
Parsing error when using nested option messages with semicolons

### ISSUE THREAD

**Issue by johanbrandhorst** [emicklei/proto#79]
As exposed by https://github.com/uber/prototool/issues/24, the following structure is unparsable by `emicklei/proto`:

```protobuf
syntax = "proto3";

import "google/api/annotations.proto";

service Test {
    rpc Test(Void) returns (Void) {
        option (google.api.http) = {
            post: "/api/v1/test";
            body: "*";
        };
    }
}

message Void {}
```

The semicolons in the option body is causing the error:
```bash
test.proto:12:1: found "}" but expected [.proto element {comment|option|import|syntax|enum|service|package|message}]
```

**Comment by emicklei** [comment]
hi, 

thank you for reporting this.
all examples i have seen of aggregated options do not use the semicolon separator.
I assume it is valid syntax.
I will create a fix for this.

**Comment by johanbrandhorst** [comment]
Indeed, as discussed in uber/prototool#24, the standard _seems_ to be to not use semicolons, but judging by the fact that `protoc` accepts it, I guess it's valid syntax? I can't find a rigorous grammatic definition for the aggregated option object.

**Comment by lucasvo** [comment]
It seems like this is fixed. Can we close this @emicklei ?

**Comment by peter-edge** [comment]
Per our convo on https://github.com/uber/prototool/issues/69, we don't think this is fixed, can we verify with the cases posted there?
